import Head from "next/head";
import styles from "../../../../styles/sucursal.module.css";
import ReturnArrow from "@/Components/ReturnArrow";
import sucursal from "../../../../../public/images/store/delivery/sucursal.png";
import Image from "next/image";

export default function Subsidiary() {
  return (
    <>
      <Head>
        <title>Best App Ever - almacen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReturnArrow href="/almacen/envios" />
      <figure className={styles.sucursal}>
        <Image height={64} width={64} src={sucursal} alt="sucursal" />
        <figcaption>Sucursal</figcaption>
      </figure>
      <div className={styles.deliveryInfo}>
        <table className={styles.table}>
          <thead className={styles.tableHeader}>
            <tr>
              <th>ID</th>
              <th>Fecha</th>
              <th>Estado</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className={styles.tableContent}>Body content 1</td>
              <td className={styles.tableContent}>Body content 2</td>
              <td className={styles.tableContent}>Body content 3</td>
              <td className={styles.tableContent}>Body content 4</td>
            </tr>
          </tbody>
        </table>
      </div>
    </>
  );
}
