import Head from "next/head";
import styles from "../../../../styles/sucursal.module.css";
import ReturnArrow from "@/Components/ReturnArrow";
import sucursal from "../../../../../public/images/store/delivery/sucursal.png";
import Image from "next/image";
import { useEffect, useState } from "react";
import { ENVIOS_STATUS } from "@/constants/envios";

export default function Subsidiary() {
  const [users, setUsers] = useState();

  useEffect(() => {
    fetch("/api/entidades/usuarios")
      .then((res) => res.json())
      .then(setUsers);
  }, []);
  console.log(users);
  return (
    <>
      <Head>
        <title>Best App Ever - almacen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReturnArrow href="/almacen/envios" />
      <figure className={styles.sucursal}>
        <Image height={64} width={64} src={sucursal} alt="sucursal" />
        <figcaption>Sucursal</figcaption>
      </figure>
      <div className={styles.deliveryInfo}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th className={styles.tableHeader}>#</th>
              <th className={styles.tableHeader}>Fecha</th>
              <th className={styles.tableHeader}>Estado</th>
              <th className={styles.tableHeader}>Acciones</th>
            </tr>
          </thead>

          {users?.map((user, index) => {
            return (
              <tbody key={index}>
                {user.envios?.map((envio, index) => {
                  if (envio.tipo_envio === ENVIOS_STATUS.SUCURSAL)
                    return (
                      <tr className={styles.tableRow} key={index}>
                        <td className={styles.tableData}>{envio.id_envio}</td>
                        <td className={styles.tableData}>{envio.fecha}</td>
                        <td className={styles.tableData}>
                          {envio.estado_envio}
                        </td>
                        <td className={styles.tableData}></td>
                      </tr>
                    );
                })}
              </tbody>
            );
          })}
        </table>
      </div>
    </>
  );
}
