import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import residence from "../../../../public/images/store/delivery/domicilio.png";
import subsidiary from "../../../../public/images/store/delivery/sucursal.png";
import StoreNavbar from "@/Components/StoreNavbar";
import styles from "../../../styles/delivery.module.css";

export default function Delivery() {
  return (
    <>
      <Head>
        <title>Best App Ever - almacen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Envíos</h1>
      <div className={styles.deliveryBtns}>
        <Link className={styles.residence} href="/almacen/envios/domicilio">
          <Image height={64} width={64} src={residence} alt="domicilio" />
          <h2>Domicilio</h2>
        </Link>
        <Link className={styles.subsidiary} href="/almacen/envios/sucursal">
          <Image height={64} width={64} src={subsidiary} alt="sucursal" />
          <h2>Sucursal</h2>
        </Link>
      </div>
      <StoreNavbar />
    </>
  );
}
