import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../../styles/envios.module.css";
import domicilio from "../../../../public/images/store/delivery/domicilio.png";
import sucursal from "../../../../public/images/store/delivery/sucursal.png";
import ReturnArrow from "@/Components/ReturnArrow";

export default function Envios() {
  return (
    <>
      <Head>
        <title>Best App Ever - almacen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReturnArrow href="/almacen" />
      <h1 className={styles.title}>Envíos</h1>
      <div className={styles.deliveryBtns}>
        <Link className={styles.residenceBtn} href="/almacen/envios/domicilio">
          <Image height={64} width={64} src={domicilio} alt="domicilio" />
          <h2>Domicilio</h2>
        </Link>
        <Link className={styles.subsidiaryBtn} href="/almacen/envios/sucursal">
          <Image height={64} width={64} src={sucursal} alt="sucursal" />
          <h2>Sucursal</h2>
        </Link>
      </div>
    </>
  );
}
