import StoreNavbar from "@/Components/StoreNavbar";
import Head from "next/head";

export default function Residence() {
  return (
    <>
      <Head>
        <title>Best App Ever - almacen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Domicilio</h1>
      <StoreNavbar />
    </>
  );
}
